core:
  name: "demo"

  addr: "0.0.0.0:8080"
  debug: false

  metrics_username: "test"
  metrics_password: "test"

  secret: "test123123"

db:
  addr: "host.docker.internal:3306"
  user: "root"
  password: "123qwe"
  database: "test"
  max_open_conn: 10
  max_idle_conn: 2

cache:
  addr: "host.docker.internal:6379"
  password: ""
  db: 0